baseurl = "/"
defaultContentLanguage = "en"
destination = "../dist/"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true
hrefTargetBlank = false
languageCode = "en-us"
languageLang = "en"
relativeURLs = false
title = "Entrada Ventures"
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[params]
author = "Xentez"
description = "Entrada Ventures is made up of several veteran angel investors and entrepreneurs who have come together to help companies make the transition from an Early Stage Startup to a \"Series A” round of professional venture capital investments."
[taxonomies]
category = "categories"
tag = "tags"
