---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: ''
sections:
- type: directory
  path: hugo/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: hugo/content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/investments
  label: Investments
  create: all
  match: "**/*"
upload_dir: src/img/uploads
public_path: img/uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: '0.45'
